### ISSUE TITLE
Find matches for org.openrewrite.java.logging.ParameterizedLogging

### ISSUE THREAD

**Issue by koppor** [openrewrite/rewrite-logging-frameworks#135]
I am using https://app.moderne.io/ (and also locally)

Go to https://app.moderne.io/, select "JabRef" and run `org.openrewrite.java.logging.slf4j.ParameterizedLogging`

There are 0 results reported:

![image](https://github.com/openrewrite/rewrite-logging-frameworks/assets/1366654/e4380db0-8a83-4ebb-bfa5-67f1f0b9078b)

However, there should be more than 1:

![image](https://github.com/openrewrite/rewrite-logging-frameworks/assets/1366654/94393cbb-e54a-4f5f-a0d7-c8083150c2e5)

That source code is also available at https://github.com/jabref/jabref/.

**Comment by koppor** [comment]
I tried

```yaml
  - org.openrewrite.java.logging.slf4j.Slf4jBestPractices
  - org.openrewrite.java.logging.ParameterizedLogging:
      methodPattern: org.slf4j.Logger error(..)
```

The latter to match the original PR content. Still no changes applied to the code base.

I asked at https://rewriteoss.slack.com/archives/C01A843MWG5/p1704459019395649 for a end-to-end test. So that one can set breakpoints and see how the whole system behaves. Currently, I am not able to set a breakpoint in the recipe and debug it with my code base.
