### ISSUE TITLE
Log4j1 to Log4j2 rewrite not complete

### ISSUE THREAD

**Issue by jocwurs** [openrewrite/rewrite-logging-frameworks#147]
## What version of OpenRewrite are you using?

I am using
Maven Plugin

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a single module project.
```xml
<project>
  <build>
    <plugins>
      <plugin>
        <groupId>org.openrewrite.maven</groupId>
        <artifactId>rewrite-maven-plugin</artifactId>
        <version>5.30.0</version>
        <configuration>
          <activeRecipes>
            <recipe>org.openrewrite.java.logging.log4j.Log4j1ToLog4j2</recipe>
          </activeRecipes>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.openrewrite.recipe</groupId>
            <artifactId>rewrite-logging-frameworks</artifactId>
            <version>2.6.1</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>
  <groupId>maven.test</groupId>
  <artifactId>maven.test</artifactId>
  <version>1.0.0</version>
  <modelVersion>4.0.0</modelVersion>
  <dependencies>
  	<dependency>
  		<groupId>org.apache.logging.log4j</groupId>
  		<artifactId>log4j-api</artifactId>
  		<version>2.23.1</version>
  	</dependency>
  	<dependency>
  		<groupId>org.apache.logging.log4j</groupId>
  		<artifactId>log4j-core</artifactId>
  		<version>2.23.1</version>
  	</dependency>
  </dependencies>
</project>
```

## What is the smallest, simplest way to reproduce the problem?

```java
import org.apache.log4j.Logger;

public class Main
{
    private static final Logger LOGGER = Logger.getLogger(Main.class);
    
    public static void main(String[] args)
    {
        LOGGER.info("Hello world");
    }
}
```

## What did you expect to see?

```java
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;

public class Main
{
    private static final Logger LOGGER = LogManager.getLogger(Main.class);
    
    public static void main(String[] args)
    {
        LOGGER.info("Hello world");
    }
}
```

## What did you see instead?

```java
import org.apache.logging.log4j.Logger;

public class Main
{
    private static final Logger LOGGER = Logger.getLogger(Main.class);
    
    public static void main(String[] args)
    {
        LOGGER.info("Hello world");
    }
}
```

## What is the full stack trace of any errors you encountered?

```
No Stack Trace
```

**Comment by timtebeek** [comment]
That's unfortunate; looks like we'd need a small addition to our tests, as we do have the recipe steps:
https://github.com/openrewrite/rewrite-logging-frameworks/blob/adb5267f9296187238f270515dab7c4643c61324/src/main/resources/META-INF/rewrite/log4j.yml#L75-L77

**Comment by jocwurs** [comment]
Should this be something like that?
  - org.openrewrite.java.ChangeMethodTargetToStatic:
      methodPattern: org.apache.log4j.Logger getLogger(..)
      fullyQualifiedTargetTypeName: org.apache.logging.log4j.LogManager

**Comment by timtebeek** [comment]
Thanks for helping think through the issue! I think the best way to try that out would be by adding a unit test using the sample you've provided above, similar to the one you see here:
https://github.com/openrewrite/rewrite-logging-frameworks/blob/adb5267f9296187238f270515dab7c4643c61324/src/test/java/org/openrewrite/java/logging/log4j/Log4j1ToLog4j2Test.java#L44-L66

That one already passes because just above the lines I'd referenced earlier, we change the package such that subsequent matchers should expect a different package.
https://github.com/openrewrite/rewrite-logging-frameworks/blob/adb5267f9296187238f270515dab7c4643c61324/src/main/resources/META-INF/rewrite/log4j.yml#L72-L77

I wonder what makes your case different from the tests we already have. Do you spot any differences? 🤔

**Comment by jocwurs** [comment]
Tried something on my machine:
matchUnknownTypes: true

```
  - org.openrewrite.java.ChangeMethodTargetToStatic:
      methodPattern: org.apache.log4j.Logger getLogger(..)
      fullyQualifiedTargetTypeName: org.apache.logging.log4j.LogManager
      matchUnknownTypes: true
  - org.openrewrite.java.ChangeMethodTargetToStatic:
      methodPattern: org.apache.logging.log4j.Logger getLogger(..)
      fullyQualifiedTargetTypeName: org.apache.logging.log4j.LogManager
      matchUnknownTypes: true
  - org.openrewrite.java.ChangeMethodTargetToStatic:
      methodPattern: org.apache.log4j.Logger getRootLogger()
      fullyQualifiedTargetTypeName: org.apache.logging.log4j.LogManager
      matchUnknownTypes: true
  - org.openrewrite.java.ChangeMethodTargetToStatic:
      methodPattern: org.apache.logging.log4j.Logger getRootLogger()
      fullyQualifiedTargetTypeName: org.apache.logging.log4j.LogManager
      matchUnknownTypes: true
```

This worked:
```
[WARNING] Changes have been made to src\maven\test\Main.java by:
[WARNING]     org.openrewrite.java.logging.log4j.Log4j1ToLog4j2
[WARNING]         org.openrewrite.java.ChangePackage: {oldPackageName=org.apache.log4j, newPackageName=org.apache.logging.log4j}
[WARNING]         org.openrewrite.java.ChangeMethodTargetToStatic: {methodPattern=org.apache.log4j.Logger getLogger(..), fullyQualifiedTargetTypeName=org.apache.logging.log4j.LogManager, matchUnknownTypes=true}
[WARNING] Please review and commit the results.
[WARNING] Estimate time saved: 5m
```

Without the parameter this line is missing:
`[WARNING]         org.openrewrite.java.ChangeMethodTargetToStatic: {methodPattern=org.apache.log4j.Logger getLogger(..), fullyQualifiedTargetTypeName=org.apache.logging.log4j.LogManager, matchUnknownTypes=true}`
