### ISSUE TITLE
Log4j1ToLog4j2 recipe does not replace uses of Category

### ISSUE THREAD

**Issue by emmulator** [openrewrite/rewrite-logging-frameworks#190]
## What version of OpenRewrite are you using?

rewrite-maven-plugin: 5.46.1
rewrite-logging-frameworks: 2.18.0-SNAPSHOT

## How are you running OpenRewrite?

`mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-logging-frameworks:2.18.0-SNAPSHOT -Drewrite.activeRecipes=org.openrewrite.java.logging.log4j.Log4j1ToLog4j2 -Drewrite.exportDatatables=true`

The actual code I'm migrating is a much larger project, but I have replicated the issue with the small code sample below.

## What is the smallest, simplest way to reproduce the problem?

```java
package com.cj.example;

import org.apache.log4j.Category;

public class App {

    private static Category logger = Category.getInstance(App.class);

    public static void main( String[] args ) {

        logger.info( "Hello World!" );
    }
}
```

## What did you expect to see?

```java
package com.cj.example;

import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;

public class App {

    private static Logger logger = LogManager.getLogger(App.class);

    public static void main( String[] args ) {

        logger.info( "Hello World!" );
    }
}
```

## What did you see instead?

```java
package com.cj.example;

import org.apache.logging.log4j.Category;

public class App {

    private static Category logger = Category.getInstance(App.class);

    public static void main( String[] args ) {

        logger.info( "Hello World!" );
    }
}
```

## What is the full stack trace of any errors you encountered?

There were no errors running the recipe, but the resulting code does not compile.  The Category class does not exist in Log4j2.

**Comment by timtebeek** [comment]
Thanks for the report @emmulator ; I _think_ this could be fixed with the addition of these steps
```yaml
  - org.openrewrite.java.ChangeMethodTargetToStatic:
      methodPattern: org.apache.log4j.Category getInstance(..)
      fullyQualifiedTargetTypeName: org.apache.logging.log4j.LogManager
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: org.apache.logging.log4j.LogManager getInstance(..)
      newMethodName: getLogger
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.apache.log4j.Category
      newFullyQualifiedTypeName: org.apache.logging.log4j.Logger
```

Just before these lines:
https://github.com/openrewrite/rewrite-logging-frameworks/blob/3492463e8443a6dae646f346f38620e862242d37/src/main/resources/META-INF/rewrite/log4j.yml#L73-L75

Would you want to push that up to a PR to get it in?
