### ISSUE TITLE
org.apache.log4j.MDC not handled with Log4jToSlf4j

### ISSUE THREAD

**Issue by rdifrango** [openrewrite/rewrite-logging-frameworks#47]
org.apache.log4j.MDC not handled with org.openrewrite.java.logging.slf4j.Log4jToSlf4j.

I had code like the following:

```
import org.apache.log4j.Logger;
import org.apache.log4j.MDC;

...

try {
            requestValues.entrySet().forEach(entry -> MDC.put(entry.getKey(), entry.getValue()));
            LOGGER.info(
                    "Example with the request oriented fields such as " + requestValues.get("X-Forwarded-For") + " has been passed in");
        } finally {
            MDC.clear();
        }
```

And it properly converted everything except so it left it with:

```
import org.apache.log4j.MDC;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


try {
            requestValues.entrySet().forEach(entry -> MDC.put(entry.getKey(), entry.getValue()));
            LOGGER.info("Example with the request oriented fields such as {} has been passed in", requestValues.get("X-Forwarded-For"));
        } finally {
            MDC.clear();
        }
```

Plugin configuration:

```
<plugin>
                <groupId>org.openrewrite.maven</groupId>
                <artifactId>rewrite-maven-plugin</artifactId>
                <version>4.17.0-SNAPSHOT</version>
                <configuration>
                    <activeRecipes>
                        <recipe>org.openrewrite.java.logging.slf4j.Log4jToSlf4j</recipe>
                        <recipe>org.openrewrite.java.logging.slf4j.ParameterizedLogging</recipe>
                        <recipe>org.openrewrite.java.logging.slf4j.Slf4jLogShouldBeConstant</recipe>
                    </activeRecipes>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.openrewrite.recipe</groupId>
                        <artifactId>rewrite-logging-frameworks</artifactId>
                        <version>1.1.0-SNAPSHOT</version>
                    </dependency>
                </dependencies>
            </plugin>
```

**Comment by rdifrango** [comment]
I was able to work-around this with the following:

```
recipeList:
  # This will swamp in SLF4J MDC because its currently missed by:
  #
  # See: https://github.com/openrewrite/rewrite-logging-frameworks/issues/47
  #
  - org.openrewrite.java.ChangeType:
        oldFullyQualifiedTypeName: org.apache.log4j.MDC
        newFullyQualifiedTypeName: org.slf4j.MDC
```
