### ISSUE TITLE
Slf4jLogShouldBeConstant removes passed exception

### ISSUE THREAD

**Issue by fprochazka** [openrewrite/rewrite-logging-frameworks#95]
Enabling the recipe

```yml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.fprochazka.Experiments
recipeList:
  - org.openrewrite.java.logging.slf4j.Slf4jLogShouldBeConstant: { }
```

and letting it apply to code

```java
log.warn(String.format("Unexpected exception: %s", ex.getClass().getName()), ex);
```

produces

```patch
-        log.warn(String.format("Unexpected exception: %s", ex.getClass().getName()), ex);
+        log.warn("Unexpected exception: {}", ex.getClass().getName());
```

but it should produce

```patch
-        log.warn(String.format("Unexpected exception: %s", ex.getClass().getName()), ex);
+        log.warn("Unexpected exception: {}", ex.getClass().getName(), ex);
```
